instances:
  co_class: 'combinatorial_auction'
  co_class_kwargs:
    'n_items': 100
    'n_bids': 500

experiment:
  seed: 12345
  device: 'cuda:0'
  path_to_load_imitation_data: 'outputs/cauc_100_500/dataset/'
  max_steps: null
  num_samples: 100000
  num_epochs: 250
  epoch_log_frequency: 1
  checkpoint_log_frequency: 1

agent:
  name: 'il'
  suffix: ''
  checkpoint: 'models/il/combinatorial_auction.pkl'
