instances:
  co_class: 'knapsack'
  co_class_kwargs:
    number_of_items: 100
    number_of_knapsacks: 6

experiment:
  seed: 12345
  device: 'cuda:0'
  path_to_load_imitation_data: 'outputs/knapsack_100_6/dataset/'
  max_steps: null
  num_samples: 100000
  num_epochs: 200
  epoch_log_frequency: 1
  checkpoint_log_frequency: 1

agent:
  name: 'il'
  suffix: ''
  checkpoint: 'models/il/knapsack.pkl'
