instances:
  co_class: 'set_covering'
  co_class_kwargs:
    'n_rows': 400
    'n_cols': 750

experiment:
  seed: 12345
  device: 'cuda:0'
  path_to_load_imitation_data: 'outputs/set_covering_400_750/dataset/'
  max_steps: null
  num_samples: 100000
  num_epochs: 250
  epoch_log_frequency: 1
  checkpoint_log_frequency: 1

agent:
  name: 'il'
  suffix: ''
  checkpoint: 'models/il/set_covering.pkl'
