instances:
  co_class: 'knapsack'
  co_class_kwargs:
    number_of_items: 100
    number_of_knapsacks: 6


experiment:
  seed: 12345
  device: 'cuda:0'
  num_updates: 100000
  buffer_max_size: 100000
  buffer_start_size: 1000
  eval_freq: 5000


agent:
  name: 'dqn'
  suffix: ''
  checkpoint: 'models/dqn/knapsack.pkl'
