instances:
  co_class: 'ucfl'
  co_class_kwargs:
    n_customers: 35
    n_facilities: 35
    ratio: 5


experiment:
  seed: 12345
  device: 'cuda:0'
  num_updates: 100000
  buffer_max_size: 100000
  buffer_start_size: 1000
  eval_freq: 5000


agent:
  name: 'dqn'
  suffix: ''
  checkpoint: 'models/dqn/ucfl.pkl'
